// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryayawinbkffrjhgxpcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5YXlhd2luYmtmZnJqaGd4cGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDgwNzYsImV4cCI6MjA2MDIyNDA3Nn0.XivITUK2ZXvJ7W73eL6I_MlXTWJehEbPCCSFXiR3C4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);